version: "3"

services:
  book_store_user_db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: book_store_user_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_store_user_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 33094:3306
